name: Release cmd-helper

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build for all platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o cmd-helper-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o cmd-helper-linux-arm64
          GOOS=darwin GOARCH=amd64 go build -o cmd-helper-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o cmd-helper-darwin-arm64

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cmd-helper-linux-amd64
            cmd-helper-linux-arm64
            cmd-helper-darwin-amd64
            cmd-helper-darwin-arm64
